"""initial schema

Revision ID: 357474ec114c
Revises: 
Create Date: 2026-07-23 00:53:05.758724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '357474ec114c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quarters',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'CLOSED', name='quarter_status'), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cognitive_scores',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('quarter_id', sa.UUID(), nullable=False),
    sa.Column('dimension', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cx_states',
    sa.Column('quarter_id', sa.UUID(), nullable=False),
    sa.Column('csat_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('churn_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('support_tickets_resolved', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quarter_id')
    )
    op.create_table('decisions',
    sa.Column('quarter_id', sa.UUID(), nullable=False),
    sa.Column('workspace', sa.Enum('FINANCE', 'MARKETING', 'PRODUCT', 'SALES', 'OPERATIONS', 'CX', name='workspace'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('decision_key', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'PROCESSED', name='decision_status'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_decision_key'), 'decisions', ['decision_key'], unique=False)
    op.create_table('finance_states',
    sa.Column('quarter_id', sa.UUID(), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('expenses', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('burn_rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('runway_months', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quarter_id')
    )
    op.create_table('marketing_states',
    sa.Column('quarter_id', sa.UUID(), nullable=False),
    sa.Column('marketing_spend', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('leads_generated', sa.Integer(), nullable=False),
    sa.Column('customer_acquisition_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('brand_awareness_score', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quarter_id')
    )
    op.create_table('modifiers',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('quarter_id', sa.UUID(), nullable=False),
    sa.Column('modifier_key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quarter_id', 'modifier_key', name='uq_modifier_quarter_key')
    )
    op.create_table('operations_states',
    sa.Column('quarter_id', sa.UUID(), nullable=False),
    sa.Column('fulfillment_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('operational_efficiency_score', sa.Float(), nullable=False),
    sa.Column('incident_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quarter_id')
    )
    op.create_table('product_states',
    sa.Column('quarter_id', sa.UUID(), nullable=False),
    sa.Column('features_shipped', sa.Integer(), nullable=False),
    sa.Column('nps_score', sa.Float(), nullable=False),
    sa.Column('tech_debt_index', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quarter_id')
    )
    op.create_table('quarter_performances',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('quarter_id', sa.UUID(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('dimension_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quarter_id')
    )
    op.create_table('sales_states',
    sa.Column('quarter_id', sa.UUID(), nullable=False),
    sa.Column('pipeline_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('deals_closed', sa.Integer(), nullable=False),
    sa.Column('quota_attainment_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quarter_id')
    )
    op.create_table('decision_logs',
    sa.Column('decision_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('input_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_records',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('quarter_id', sa.UUID(), nullable=False),
    sa.Column('decision_id', sa.UUID(), nullable=False),
    sa.Column('workspace', sa.Enum('FINANCE', 'MARKETING', 'PRODUCT', 'SALES', 'OPERATIONS', 'CX', name='workspace'), nullable=False),
    sa.Column('evidence_key', sa.String(length=100), nullable=False),
    sa.Column('evidence_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('categories', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidence_records')
    op.drop_table('decision_logs')
    op.drop_table('sales_states')
    op.drop_table('quarter_performances')
    op.drop_table('product_states')
    op.drop_table('operations_states')
    op.drop_table('modifiers')
    op.drop_table('marketing_states')
    op.drop_table('finance_states')
    op.drop_index(op.f('ix_decisions_decision_key'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_table('cx_states')
    op.drop_table('cognitive_scores')
    op.drop_table('quarters')
    op.drop_table('companies')
    # ### end Alembic commands ###
